# -*- coding: utf-8 -*-
"""
Created on Wed Jun 29 09:21:57 2016

@author: Danius.silkaitis
"""

##Problem 2
#Each new term in the Fibonacci sequence is generated by adding 
#the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed 
#four million, find the sum of the even-valued terms.

prev1 = 0
prev2 = 1
new = 0
sum = 0
while new < 4e6:
    new = prev1 + prev2
    if new % 2 == 0:
        sum = sum + new
    prev1 = prev2
    prev2 = new

print 'Sum of the even valued terms:'
print sum